import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-black text-white">

<nav className="bg-zinc-900 border-b border-zinc-800 px-8 py-4 flex gap-6 text-lg">

<a href="/" className="hover:text-yellow-400 transition">
Home
</a>

<a href="/tipps" className="hover:text-yellow-400 transition">
Tipps
</a>

<a href="/tabelle" className="hover:text-yellow-400 transition">
Tabelle
</a>

<a href="/regeln" className="hover:text-yellow-400 transition">
Regeln
</a>

</nav>

{children}</body>
    </html>
  );
}
